[package]
name = "fp-dynamic-fee"
version = "1.0.0"
authors = ["Parity Technologies <admin@parity.io"]
edition = "2021"
license = "Apache-2.0"
description = "Dynamic fee inherent primitives for Ethereum RPC (web3) compatibility layer for Substrate."
repository = "https://github.com/paritytech/frontier/"

[package.metadata.docs.rs]
targets = ["x86_64-unknown-linux-gnu"]

[dependencies]
async-trait = "0.1"

# Substrate
sp-core = { version = "6.0.0", git = "https://github.com/cloudwalk/substrate", branch = "cloudwalk-polkadot-v0.9.25-aura-upgrade-to-change-authorities", default-features = false }
sp-inherents = { version = "4.0.0-dev", git = "https://github.com/cloudwalk/substrate", branch = "cloudwalk-polkadot-v0.9.25-aura-upgrade-to-change-authorities", default-features = false }

[features]
default = ["std"]
std = [
	# Substrate
	"sp-core/std",
	"sp-inherents/std",
]
