[package]
name = "pallet-evm-precompile-curve25519-benchmarking"
version = "6.0.0-dev"
license = "Apache-2.0"
readme = "README.md"
description = "FRAME EVM precompile benchmarking pallet."
authors = { workspace = true }
edition = { workspace = true }
repository = { workspace = true }

[package.metadata.docs.rs]
targets = ["x86_64-unknown-linux-gnu"]

[dependencies]
curve25519-dalek = { version = "4.1.0", default-features = false, features = ["alloc"] }
sha2 = { workspace = true }

# Substrate
frame-benchmarking = { workspace = true, default-features = false }
frame-system = { workspace = true }
sp-runtime = { workspace = true, default-features = false }

# Precompile dependencies
pallet-evm-precompile-curve25519 = { workspace = true, default-features = false }

[features]
default = ["std"]
std = [
	"sha2/std",
	# Substrate
	"frame-benchmarking/std",
	"frame-system/std",
	"sp-runtime/std",
	# Precompile dependencies
	"pallet-evm-precompile-curve25519/std",
]
runtime-benchmarks = [
	"frame-benchmarking/runtime-benchmarks",
	"frame-system/runtime-benchmarks",
	"sp-runtime/runtime-benchmarks",
]
