[package]
name = "pallet-evm-precompile-modexp"
version = "2.0.0-dev"
license = "Apache-2.0"
description = "MODEXP precompiles for EVM pallet."
authors = { workspace = true }
edition = { workspace = true }
repository = { workspace = true }

[dependencies]
num = { version = "0.4.3", default-features = false, features = ["alloc"] }
# Frontier
fp-evm = { workspace = true }

[dev-dependencies]
hex = { workspace = true }
# Frontier
pallet-evm-test-vector-support = { workspace = true }

[features]
default = ["std"]
std = [
	"num/std",
	# Frontier
	"fp-evm/std",
]
