[toolchain]
# Stable
#channel = "1.70.0" # rustc 1.70.0 (84c898d65 2023-05-13)
# Nightly
channel = "nightly-2023-05-23" # rustc 1.71.0-nightly (8b4b20836 2023-05-22)
components = ["rustfmt", "clippy"]
targets = ["wasm32-unknown-unknown"]
profile = "minimal"
