[package]
name = "frontier-rpc-primitives"
version = "0.1.0"
authors = ["Parity Technologies <admin@parity.io"]
edition = "2018"
description = "Runtime primitives for Ethereum RPC (web3) compatibility layer for Substrate."
license = "GPL-3.0"

[dependencies]
sp-core = { version = "2.0.0-dev", default-features = false, path = "../../vendor/substrate/primitives/core" }
sp-api = { version = "2.0.0-dev", default-features = false, path = "../../vendor/substrate/primitives/api" }
pallet-evm = { version = "2.0.0-dev", default-features = false, path = "../../vendor/substrate/frame/evm" }
ethereum = { version = "0.2", default-features = false, features = ["codec"] }
ethereum-types = { version = "0.9", default-features = false }
codec = { package = "parity-scale-codec", version = "1.0.0", default-features = false }
sp-runtime = { version = "2.0.0-dev", default-features = false, path = "../../vendor/substrate/primitives/runtime" }
sp-std = { version = "2.0.0-dev", default-features = false, path = "../../vendor/substrate/primitives/std" }

[features]
default = ["std"]
std = [
	"sp-core/std",
	"sp-api/std",
	"pallet-evm/std",
	"ethereum/std",
	"ethereum-types/std",
	"codec/std",
	"sp-runtime/std",
	"sp-std/std",
]
