[package]
name = "fp-self-contained"
version = "1.0.0-dev"
license = "Apache-2.0"
authors = ["Parity Technologies <admin@parity.io>"]
edition = "2021"
homepage = "https://substrate.io"
repository = "https://github.com/paritytech/frontier/"
description = "Primitive Ethereum abstractions for Substrate."
documentation = "https://docs.rs/fp-ethereum"

[dependencies]
ethereum = { version = "0.11.1", default-features = false, features = ["with-codec"] }
serde = { version = "1.0.101", features = ["derive"], optional = true }

codec = { package = "parity-scale-codec", version = "2.0.0", default-features = false }
scale-info = { version = "1.0.0", default-features = false, features = ["derive"] }
parity-util-mem = { version = "0.10", optional = true }
sp-debug-derive = { version = "4.0.0", git = "https://github.com/paritytech/substrate", branch = "master", default-features = false }
sp-runtime = { version = "5.0.0", git = "https://github.com/paritytech/substrate", branch = "master", default-features = false }
sp-io = { version = "5.0.0", git = "https://github.com/paritytech/substrate", branch = "master", default-features = false }
frame-support = { version = "4.0.0-dev", git = "https://github.com/paritytech/substrate", branch = "master", default-features = false }

[features]
default = ["std"]
std = [
	"ethereum/std",
	"serde",

	"codec/std",
	"scale-info/std",
	"parity-util-mem",
	"sp-debug-derive/std",
	"sp-runtime/std",
	"frame-support/std",
]
