[package]
name = "fp-self-contained"
version = "1.0.0-dev"
authors = ["Parity Technologies <admin@parity.io>"]
edition = "2021"
license = "Apache-2.0"
description = "Primitive Ethereum abstractions for Substrate."
repository = "https://github.com/paritytech/frontier/"

[package.metadata.docs.rs]
targets = ["x86_64-unknown-linux-gnu"]

[dependencies]
ethereum = { version = "0.12.0", default-features = false, features = ["with-codec"] }
serde = { version = "1.0.142", features = ["derive"], optional = true }

# Parity
codec = { package = "parity-scale-codec", version = "3.0.0", default-features = false }
parity-util-mem = { version = "0.11", optional = true }
scale-info = { version = "2.1.2", default-features = false, features = ["derive"] }

# Substrate
sp-runtime = { version = "6.0.0", git = "https://github.com/paritytech/substrate", branch = "master", default-features = false }
# Substrate FRAME
frame-support = { version = "4.0.0-dev", git = "https://github.com/paritytech/substrate", branch = "master", default-features = false }

[features]
default = ["std"]
std = [
	"ethereum/std",
	"serde",
	# Parity
	"codec/std",
	"parity-util-mem",
	"scale-info/std",
	# Substrate
	"sp-runtime/std",
	# Substrate FRAME
	"frame-support/std",
]
