[package]
name = "pallet-evm-precompile-simple"
version = "2.0.0-dev"
authors = ["Parity Technologies <admin@parity.io>"]
edition = "2021"
license = "Apache-2.0"
description = "Simple precompiles for EVM pallet."
repository = "https://github.com/paritytech/frontier/"

[dependencies]
ripemd = { version = "0.1", default-features = false }

# Substrate
sp-io = { version = "6.0.0", git = "https://github.com/cloudwalk/substrate", branch = "cloudwalk-polkadot-v0.9.25-aura-upgrade-to-change-authorities", default-features = false }

# Frontier
fp-evm = { version = "3.0.0-dev", path = "../../../../primitives/evm", default-features = false }

[dev-dependencies]
pallet-evm-test-vector-support = { version = "1.0.0-dev", path = "../../test-vector-support" }

[features]
default = ["std"]
std = [
	"ripemd/std",
	# Substrate
	"sp-io/std",
	# Frontier
	"fp-evm/std",
]
