[package]
name = "ethereum-rpc"
version = "0.1.0"
authors = ["Parity Technologies <admin@parity.io>"]
edition = "2018"
description = "RPC traits of Ethereum."
license = "GPL-3.0"

[dependencies]
jsonrpc-core = "14.0.3"
jsonrpc-core-client = "14.0.3"
jsonrpc-derive = "14.0.3"
jsonrpc-pubsub = "14.0.5"
rustc-hex = "2.1.0"
ethereum-types = "0.8.0"
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
