[package]
name = "pallet-evm-precompile-dispatch"
version = "2.0.0-dev"
authors = ["Parity Technologies <admin@parity.io>"]
edition = "2021"
license = "Apache-2.0"
description = "DISPATCH precompiles for EVM pallet."
repository = "https://github.com/paritytech/frontier/"

[dependencies]
# Substrate FRAME
frame-support = { version = "4.0.0-dev", git = "https://github.com/paritytech/substrate", branch = "master", default-features = false }

# Frontier
fp-evm = { version = "3.0.0-dev", path = "../../../../primitives/evm", default-features = false }
pallet-evm = { version = "6.0.0-dev", path = "../..", default-features = false }

[features]
default = ["std"]
std = [
	# Substrate FRAME
	"frame-support/std",
	# Frontier
	"fp-evm/std",
	"pallet-evm/std",
]
