name: Cancel

on:
  push:
    branches:
      - '**'
      - '!master'
      - '!polkadot-v**'

jobs:
  cancel:
    name: 'Cancel previous runs'
    runs-on: ubuntu-latest
    timeout-minutes: 3
    steps:
      - uses: styfle/cancel-workflow-action@0.12.1
        with:
          workflow_id: 1303397
          access_token: ${{ github.token }}
